/*
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.manticoresearch.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.manticoresearch.client.JSON;


/**
 * Aggregation group returned under &#x60;aggregations&#x60;
 */
@JsonPropertyOrder({
  AggBucketsResult.JSON_PROPERTY_BUCKETS,
  AggBucketsResult.JSON_PROPERTY_AFTER_KEY
})
@JsonTypeName("aggBucketsResult")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-15T06:32:20.081730672Z[Etc/UTC]", comments = "Generator version: 7.17.0")
public class AggBucketsResult {
  public static final String JSON_PROPERTY_BUCKETS = "buckets";
  private JsonNullable<Object> buckets = JsonNullable.<Object>undefined();

  public static final String JSON_PROPERTY_AFTER_KEY = "after_key";
  private Object afterKey;

  public AggBucketsResult() { 
  }

  public AggBucketsResult buckets(Object buckets) {
    this.buckets = JsonNullable.<Object>of(buckets);
    return this;
  }

  /**
   * Get buckets
   * @return buckets
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Object getBuckets() {
        return buckets.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_BUCKETS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Object> getBuckets_JsonNullable() {
    return buckets;
  }
  
  @JsonProperty(JSON_PROPERTY_BUCKETS)
  public void setBuckets_JsonNullable(JsonNullable<Object> buckets) {
    this.buckets = buckets;
  }

  public void setBuckets(Object buckets) {
    this.buckets = JsonNullable.<Object>of(buckets);
  }


  public AggBucketsResult afterKey(Object afterKey) {
    this.afterKey = afterKey;
    return this;
  }

  /**
   * Pagination cursor returned by composite aggregations
   * @return afterKey
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AFTER_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getAfterKey() {
    return afterKey;
  }


  @JsonProperty(JSON_PROPERTY_AFTER_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAfterKey(Object afterKey) {
    this.afterKey = afterKey;
  }

  /**
   * Return true if this aggBucketsResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AggBucketsResult aggBucketsResult = (AggBucketsResult) o;
    return equalsNullable(this.buckets, aggBucketsResult.buckets) &&
        Objects.equals(this.afterKey, aggBucketsResult.afterKey);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(buckets), afterKey);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AggBucketsResult {\n");
    sb.append("    buckets: ").append(toIndentedString(buckets)).append("\n");
    sb.append("    afterKey: ").append(toIndentedString(afterKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

