/*
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.manticoresearch.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.manticoresearch.client.model.FacetBucketStatus;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.manticoresearch.client.JSON;


/**
 * Single bucket in an aggregation result
 */
@JsonPropertyOrder({
  AggBucket.JSON_PROPERTY_KEY,
  AggBucket.JSON_PROPERTY_DOC_COUNT,
  AggBucket.JSON_PROPERTY_STATUS
})
@JsonTypeName("aggBucket")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-15T06:32:20.081730672Z[Etc/UTC]", comments = "Generator version: 7.17.0")
public class AggBucket {
  public static final String JSON_PROPERTY_KEY = "key";
  private JsonNullable<Object> key = JsonNullable.<Object>undefined();

  public static final String JSON_PROPERTY_DOC_COUNT = "doc_count";
  private Integer docCount;

  public static final String JSON_PROPERTY_STATUS = "status";
  private FacetBucketStatus status;

  public AggBucket() { 
  }

  public AggBucket key(Object key) {
    this.key = JsonNullable.<Object>of(key);
    return this;
  }

  /**
   * Get key
   * @return key
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Object getKey() {
        return key.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<Object> getKey_JsonNullable() {
    return key;
  }
  
  @JsonProperty(JSON_PROPERTY_KEY)
  public void setKey_JsonNullable(JsonNullable<Object> key) {
    this.key = key;
  }

  public void setKey(Object key) {
    this.key = JsonNullable.<Object>of(key);
  }


  public AggBucket docCount(Integer docCount) {
    this.docCount = docCount;
    return this;
  }

  /**
   * Number of documents in the bucket
   * @return docCount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DOC_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getDocCount() {
    return docCount;
  }


  @JsonProperty(JSON_PROPERTY_DOC_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDocCount(Integer docCount) {
    this.docCount = docCount;
  }


  public AggBucket status(FacetBucketStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FacetBucketStatus getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(FacetBucketStatus status) {
    this.status = status;
  }

  /**
   * Return true if this aggBucket object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AggBucket aggBucket = (AggBucket) o;
    return equalsNullable(this.key, aggBucket.key) &&
        Objects.equals(this.docCount, aggBucket.docCount) &&
        Objects.equals(this.status, aggBucket.status);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(key), docCount, status);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AggBucket {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    docCount: ").append(toIndentedString(docCount)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

