/*
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.manticoresearch.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.manticoresearch.client.model.AggTDigest;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.manticoresearch.client.JSON;


/**
 * Object to use percentile ranks in aggregation. For more information see [Grouping](https://manual.manticoresearch.com/Searching/Grouping#PERCENTILE_RANKS(),-MEDIAN_ABSOLUTE_DEVIATION()) 
 */
@JsonPropertyOrder({
  AggPercentileRanks.JSON_PROPERTY_FIELD,
  AggPercentileRanks.JSON_PROPERTY_VALUES,
  AggPercentileRanks.JSON_PROPERTY_KEYED,
  AggPercentileRanks.JSON_PROPERTY_TDIGEST
})
@JsonTypeName("aggPercentileRanks")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-15T06:32:20.081730672Z[Etc/UTC]", comments = "Generator version: 7.17.0")
public class AggPercentileRanks {
  public static final String JSON_PROPERTY_FIELD = "field";
  private String field;

  public static final String JSON_PROPERTY_VALUES = "values";
  private List<BigDecimal> values = new ArrayList<>();

  public static final String JSON_PROPERTY_KEYED = "keyed";
  private Boolean keyed;

  public static final String JSON_PROPERTY_TDIGEST = "tdigest";
  private AggTDigest tdigest;

  public AggPercentileRanks() { 
  }

  public AggPercentileRanks field(String field) {
    this.field = field;
    return this;
  }

  /**
   * Numeric field to calculate percentile ranks for
   * @return field
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getField() {
    return field;
  }


  @JsonProperty(JSON_PROPERTY_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setField(String field) {
    this.field = field;
  }


  public AggPercentileRanks values(List<BigDecimal> values) {
    this.values = values;
    return this;
  }

  public AggPercentileRanks addValuesItem(BigDecimal valuesItem) {
    if (this.values == null) {
      this.values = new ArrayList<>();
    }
    this.values.add(valuesItem);
    return this;
  }

  /**
   * Input values to rank
   * @return values
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VALUES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<BigDecimal> getValues() {
    return values;
  }


  @JsonProperty(JSON_PROPERTY_VALUES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValues(List<BigDecimal> values) {
    this.values = values;
  }


  public AggPercentileRanks keyed(Boolean keyed) {
    this.keyed = keyed;
    return this;
  }

  /**
   * Return an object keyed by input value when true, or an array when false. Default is false. 
   * @return keyed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEYED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getKeyed() {
    return keyed;
  }


  @JsonProperty(JSON_PROPERTY_KEYED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeyed(Boolean keyed) {
    this.keyed = keyed;
  }


  public AggPercentileRanks tdigest(AggTDigest tdigest) {
    this.tdigest = tdigest;
    return this;
  }

  /**
   * Get tdigest
   * @return tdigest
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TDIGEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AggTDigest getTdigest() {
    return tdigest;
  }


  @JsonProperty(JSON_PROPERTY_TDIGEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTdigest(AggTDigest tdigest) {
    this.tdigest = tdigest;
  }

  /**
   * Return true if this aggPercentileRanks object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AggPercentileRanks aggPercentileRanks = (AggPercentileRanks) o;
    return Objects.equals(this.field, aggPercentileRanks.field) &&
        Objects.equals(this.values, aggPercentileRanks.values) &&
        Objects.equals(this.keyed, aggPercentileRanks.keyed) &&
        Objects.equals(this.tdigest, aggPercentileRanks.tdigest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(field, values, keyed, tdigest);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AggPercentileRanks {\n");
    sb.append("    field: ").append(toIndentedString(field)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("    keyed: ").append(toIndentedString(keyed)).append("\n");
    sb.append("    tdigest: ").append(toIndentedString(tdigest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

