/*
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.manticoresearch.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.manticoresearch.client.model.Range;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.manticoresearch.client.JSON;


/**
 * Group documents into custom numeric or date ranges. Use with the &#x60;range&#x60; or &#x60;date_range&#x60; aggregation type. 
 */
@JsonPropertyOrder({
  AggRange.JSON_PROPERTY_FIELD,
  AggRange.JSON_PROPERTY_RANGES,
  AggRange.JSON_PROPERTY_KEYED
})
@JsonTypeName("aggRange")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-15T17:05:43.549629793Z[Etc/UTC]", comments = "Generator version: 7.17.0")
public class AggRange {
  public static final String JSON_PROPERTY_FIELD = "field";
  private String field;

  public static final String JSON_PROPERTY_RANGES = "ranges";
  private List<Range> ranges = new ArrayList<>();

  public static final String JSON_PROPERTY_KEYED = "keyed";
  private Boolean keyed;

  public AggRange() { 
  }

  public AggRange field(String field) {
    this.field = field;
    return this;
  }

  /**
   * Attribute to group by
   * @return field
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getField() {
    return field;
  }


  @JsonProperty(JSON_PROPERTY_FIELD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setField(String field) {
    this.field = field;
  }


  public AggRange ranges(List<Range> ranges) {
    this.ranges = ranges;
    return this;
  }

  public AggRange addRangesItem(Range rangesItem) {
    if (this.ranges == null) {
      this.ranges = new ArrayList<>();
    }
    this.ranges.add(rangesItem);
    return this;
  }

  /**
   * Ordered list of ranges
   * @return ranges
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RANGES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Range> getRanges() {
    return ranges;
  }


  @JsonProperty(JSON_PROPERTY_RANGES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRanges(List<Range> ranges) {
    this.ranges = ranges;
  }


  public AggRange keyed(Boolean keyed) {
    this.keyed = keyed;
    return this;
  }

  /**
   * Return buckets as an object keyed by range label when true, or as an array when false. Default is false. 
   * @return keyed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEYED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getKeyed() {
    return keyed;
  }


  @JsonProperty(JSON_PROPERTY_KEYED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeyed(Boolean keyed) {
    this.keyed = keyed;
  }

  /**
   * Return true if this aggRange object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AggRange aggRange = (AggRange) o;
    return Objects.equals(this.field, aggRange.field) &&
        Objects.equals(this.ranges, aggRange.ranges) &&
        Objects.equals(this.keyed, aggRange.keyed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(field, ranges, keyed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AggRange {\n");
    sb.append("    field: ").append(toIndentedString(field)).append("\n");
    sb.append("    ranges: ").append(toIndentedString(ranges)).append("\n");
    sb.append("    keyed: ").append(toIndentedString(keyed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

