/*
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.manticoresearch.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.manticoresearch.client.model.AggComposite;
import com.manticoresearch.client.model.AggDateHistogram;
import com.manticoresearch.client.model.AggHistogram;
import com.manticoresearch.client.model.AggMedianAbsoluteDeviation;
import com.manticoresearch.client.model.AggMetric;
import com.manticoresearch.client.model.AggPercentileRanks;
import com.manticoresearch.client.model.AggPercentiles;
import com.manticoresearch.client.model.AggRange;
import com.manticoresearch.client.model.AggTerms;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.manticoresearch.client.JSON;


/**
 * Aggregation
 */
@JsonPropertyOrder({
  Aggregation.JSON_PROPERTY_TERMS,
  Aggregation.JSON_PROPERTY_SORT,
  Aggregation.JSON_PROPERTY_COMPOSITE,
  Aggregation.JSON_PROPERTY_HISTOGRAM,
  Aggregation.JSON_PROPERTY_DATE_HISTOGRAM,
  Aggregation.JSON_PROPERTY_RANGE,
  Aggregation.JSON_PROPERTY_DATE_RANGE,
  Aggregation.JSON_PROPERTY_PERCENTILES,
  Aggregation.JSON_PROPERTY_PERCENTILE_RANKS,
  Aggregation.JSON_PROPERTY_MEDIAN_ABSOLUTE_DEVIATION,
  Aggregation.JSON_PROPERTY_MIN,
  Aggregation.JSON_PROPERTY_MAX,
  Aggregation.JSON_PROPERTY_SUM,
  Aggregation.JSON_PROPERTY_AVG
})
@JsonTypeName("aggregation")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-15T17:05:43.549629793Z[Etc/UTC]", comments = "Generator version: 7.17.0")
public class Aggregation {
  public static final String JSON_PROPERTY_TERMS = "terms";
  private AggTerms terms;

  public static final String JSON_PROPERTY_SORT = "sort";
  private List<Object> sort = new ArrayList<>();

  public static final String JSON_PROPERTY_COMPOSITE = "composite";
  private AggComposite composite;

  public static final String JSON_PROPERTY_HISTOGRAM = "histogram";
  private AggHistogram histogram;

  public static final String JSON_PROPERTY_DATE_HISTOGRAM = "date_histogram";
  private AggDateHistogram dateHistogram;

  public static final String JSON_PROPERTY_RANGE = "range";
  private AggRange range;

  public static final String JSON_PROPERTY_DATE_RANGE = "date_range";
  private AggRange dateRange;

  public static final String JSON_PROPERTY_PERCENTILES = "percentiles";
  private AggPercentiles percentiles;

  public static final String JSON_PROPERTY_PERCENTILE_RANKS = "percentile_ranks";
  private AggPercentileRanks percentileRanks;

  public static final String JSON_PROPERTY_MEDIAN_ABSOLUTE_DEVIATION = "median_absolute_deviation";
  private AggMedianAbsoluteDeviation medianAbsoluteDeviation;

  public static final String JSON_PROPERTY_MIN = "min";
  private AggMetric min;

  public static final String JSON_PROPERTY_MAX = "max";
  private AggMetric max;

  public static final String JSON_PROPERTY_SUM = "sum";
  private AggMetric sum;

  public static final String JSON_PROPERTY_AVG = "avg";
  private AggMetric avg;

  public Aggregation() { 
  }

  public Aggregation terms(AggTerms terms) {
    this.terms = terms;
    return this;
  }

  /**
   * Get terms
   * @return terms
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TERMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AggTerms getTerms() {
    return terms;
  }


  @JsonProperty(JSON_PROPERTY_TERMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTerms(AggTerms terms) {
    this.terms = terms;
  }


  public Aggregation sort(List<Object> sort) {
    this.sort = sort;
    return this;
  }

  public Aggregation addSortItem(Object sortItem) {
    if (this.sort == null) {
      this.sort = new ArrayList<>();
    }
    this.sort.add(sortItem);
    return this;
  }

  /**
   * Get sort
   * @return sort
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getSort() {
    return sort;
  }


  @JsonProperty(JSON_PROPERTY_SORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSort(List<Object> sort) {
    this.sort = sort;
  }


  public Aggregation composite(AggComposite composite) {
    this.composite = composite;
    return this;
  }

  /**
   * Get composite
   * @return composite
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPOSITE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AggComposite getComposite() {
    return composite;
  }


  @JsonProperty(JSON_PROPERTY_COMPOSITE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComposite(AggComposite composite) {
    this.composite = composite;
  }


  public Aggregation histogram(AggHistogram histogram) {
    this.histogram = histogram;
    return this;
  }

  /**
   * Get histogram
   * @return histogram
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HISTOGRAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AggHistogram getHistogram() {
    return histogram;
  }


  @JsonProperty(JSON_PROPERTY_HISTOGRAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHistogram(AggHistogram histogram) {
    this.histogram = histogram;
  }


  public Aggregation dateHistogram(AggDateHistogram dateHistogram) {
    this.dateHistogram = dateHistogram;
    return this;
  }

  /**
   * Get dateHistogram
   * @return dateHistogram
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE_HISTOGRAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AggDateHistogram getDateHistogram() {
    return dateHistogram;
  }


  @JsonProperty(JSON_PROPERTY_DATE_HISTOGRAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateHistogram(AggDateHistogram dateHistogram) {
    this.dateHistogram = dateHistogram;
  }


  public Aggregation range(AggRange range) {
    this.range = range;
    return this;
  }

  /**
   * Get range
   * @return range
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AggRange getRange() {
    return range;
  }


  @JsonProperty(JSON_PROPERTY_RANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRange(AggRange range) {
    this.range = range;
  }


  public Aggregation dateRange(AggRange dateRange) {
    this.dateRange = dateRange;
    return this;
  }

  /**
   * Get dateRange
   * @return dateRange
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE_RANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AggRange getDateRange() {
    return dateRange;
  }


  @JsonProperty(JSON_PROPERTY_DATE_RANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateRange(AggRange dateRange) {
    this.dateRange = dateRange;
  }


  public Aggregation percentiles(AggPercentiles percentiles) {
    this.percentiles = percentiles;
    return this;
  }

  /**
   * Get percentiles
   * @return percentiles
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERCENTILES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AggPercentiles getPercentiles() {
    return percentiles;
  }


  @JsonProperty(JSON_PROPERTY_PERCENTILES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPercentiles(AggPercentiles percentiles) {
    this.percentiles = percentiles;
  }


  public Aggregation percentileRanks(AggPercentileRanks percentileRanks) {
    this.percentileRanks = percentileRanks;
    return this;
  }

  /**
   * Get percentileRanks
   * @return percentileRanks
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERCENTILE_RANKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AggPercentileRanks getPercentileRanks() {
    return percentileRanks;
  }


  @JsonProperty(JSON_PROPERTY_PERCENTILE_RANKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPercentileRanks(AggPercentileRanks percentileRanks) {
    this.percentileRanks = percentileRanks;
  }


  public Aggregation medianAbsoluteDeviation(AggMedianAbsoluteDeviation medianAbsoluteDeviation) {
    this.medianAbsoluteDeviation = medianAbsoluteDeviation;
    return this;
  }

  /**
   * Get medianAbsoluteDeviation
   * @return medianAbsoluteDeviation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MEDIAN_ABSOLUTE_DEVIATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AggMedianAbsoluteDeviation getMedianAbsoluteDeviation() {
    return medianAbsoluteDeviation;
  }


  @JsonProperty(JSON_PROPERTY_MEDIAN_ABSOLUTE_DEVIATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMedianAbsoluteDeviation(AggMedianAbsoluteDeviation medianAbsoluteDeviation) {
    this.medianAbsoluteDeviation = medianAbsoluteDeviation;
  }


  public Aggregation min(AggMetric min) {
    this.min = min;
    return this;
  }

  /**
   * Get min
   * @return min
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AggMetric getMin() {
    return min;
  }


  @JsonProperty(JSON_PROPERTY_MIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMin(AggMetric min) {
    this.min = min;
  }


  public Aggregation max(AggMetric max) {
    this.max = max;
    return this;
  }

  /**
   * Get max
   * @return max
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AggMetric getMax() {
    return max;
  }


  @JsonProperty(JSON_PROPERTY_MAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMax(AggMetric max) {
    this.max = max;
  }


  public Aggregation sum(AggMetric sum) {
    this.sum = sum;
    return this;
  }

  /**
   * Get sum
   * @return sum
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AggMetric getSum() {
    return sum;
  }


  @JsonProperty(JSON_PROPERTY_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSum(AggMetric sum) {
    this.sum = sum;
  }


  public Aggregation avg(AggMetric avg) {
    this.avg = avg;
    return this;
  }

  /**
   * Get avg
   * @return avg
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AVG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AggMetric getAvg() {
    return avg;
  }


  @JsonProperty(JSON_PROPERTY_AVG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvg(AggMetric avg) {
    this.avg = avg;
  }

  /**
   * Return true if this aggregation object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Aggregation aggregation = (Aggregation) o;
    return Objects.equals(this.terms, aggregation.terms) &&
        Objects.equals(this.sort, aggregation.sort) &&
        Objects.equals(this.composite, aggregation.composite) &&
        Objects.equals(this.histogram, aggregation.histogram) &&
        Objects.equals(this.dateHistogram, aggregation.dateHistogram) &&
        Objects.equals(this.range, aggregation.range) &&
        Objects.equals(this.dateRange, aggregation.dateRange) &&
        Objects.equals(this.percentiles, aggregation.percentiles) &&
        Objects.equals(this.percentileRanks, aggregation.percentileRanks) &&
        Objects.equals(this.medianAbsoluteDeviation, aggregation.medianAbsoluteDeviation) &&
        Objects.equals(this.min, aggregation.min) &&
        Objects.equals(this.max, aggregation.max) &&
        Objects.equals(this.sum, aggregation.sum) &&
        Objects.equals(this.avg, aggregation.avg);
  }

  @Override
  public int hashCode() {
    return Objects.hash(terms, sort, composite, histogram, dateHistogram, range, dateRange, percentiles, percentileRanks, medianAbsoluteDeviation, min, max, sum, avg);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Aggregation {\n");
    sb.append("    terms: ").append(toIndentedString(terms)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    composite: ").append(toIndentedString(composite)).append("\n");
    sb.append("    histogram: ").append(toIndentedString(histogram)).append("\n");
    sb.append("    dateHistogram: ").append(toIndentedString(dateHistogram)).append("\n");
    sb.append("    range: ").append(toIndentedString(range)).append("\n");
    sb.append("    dateRange: ").append(toIndentedString(dateRange)).append("\n");
    sb.append("    percentiles: ").append(toIndentedString(percentiles)).append("\n");
    sb.append("    percentileRanks: ").append(toIndentedString(percentileRanks)).append("\n");
    sb.append("    medianAbsoluteDeviation: ").append(toIndentedString(medianAbsoluteDeviation)).append("\n");
    sb.append("    min: ").append(toIndentedString(min)).append("\n");
    sb.append("    max: ").append(toIndentedString(max)).append("\n");
    sb.append("    sum: ").append(toIndentedString(sum)).append("\n");
    sb.append("    avg: ").append(toIndentedString(avg)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

