/*
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 3.3.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.manticoresearch.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.manticoresearch.client.JSON;


/**
 * Boolean attribute filter
 */
@JsonPropertyOrder({
  BoolFilter.JSON_PROPERTY_SHOULD,
  BoolFilter.JSON_PROPERTY_MUST,
  BoolFilter.JSON_PROPERTY_MUST_NOT
})
@JsonTypeName("boolFilter")
@JsonIgnoreProperties(ignoreUnknown = true)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-04T05:37:39.929867Z[Etc/UTC]")
public class BoolFilter {
  public static final String JSON_PROPERTY_SHOULD = "should";
  private List<Object> should;

  public static final String JSON_PROPERTY_MUST = "must";
  private List<Object> must;

  public static final String JSON_PROPERTY_MUST_NOT = "must_not";
  private List<Object> mustNot;

  public BoolFilter() { 
  }

  public BoolFilter should(List<Object> should) {
    this.should = should;
    return this;
  }

  public BoolFilter addShouldItem(Object shouldItem) {
    if (this.should == null) {
      this.should = new ArrayList<>();
    }
    this.should.add(shouldItem);
    return this;
  }

   /**
   * Get should
   * @return should
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHOULD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getShould() {
    return should;
  }


  @JsonProperty(JSON_PROPERTY_SHOULD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShould(List<Object> should) {
    this.should = should;
  }


  public BoolFilter must(List<Object> must) {
    this.must = must;
    return this;
  }

  public BoolFilter addMustItem(Object mustItem) {
    if (this.must == null) {
      this.must = new ArrayList<>();
    }
    this.must.add(mustItem);
    return this;
  }

   /**
   * Get must
   * @return must
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MUST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getMust() {
    return must;
  }


  @JsonProperty(JSON_PROPERTY_MUST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMust(List<Object> must) {
    this.must = must;
  }


  public BoolFilter mustNot(List<Object> mustNot) {
    this.mustNot = mustNot;
    return this;
  }

  public BoolFilter addMustNotItem(Object mustNotItem) {
    if (this.mustNot == null) {
      this.mustNot = new ArrayList<>();
    }
    this.mustNot.add(mustNotItem);
    return this;
  }

   /**
   * Get mustNot
   * @return mustNot
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MUST_NOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getMustNot() {
    return mustNot;
  }


  @JsonProperty(JSON_PROPERTY_MUST_NOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMustNot(List<Object> mustNot) {
    this.mustNot = mustNot;
  }


  /**
   * Return true if this boolFilter object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoolFilter boolFilter = (BoolFilter) o;
    return Objects.equals(this.should, boolFilter.should) &&
        Objects.equals(this.must, boolFilter.must) &&
        Objects.equals(this.mustNot, boolFilter.mustNot);
  }

  @Override
  public int hashCode() {
    return Objects.hash(should, must, mustNot);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoolFilter {\n");
    sb.append("    should: ").append(toIndentedString(should)).append("\n");
    sb.append("    must: ").append(toIndentedString(must)).append("\n");
    sb.append("    mustNot: ").append(toIndentedString(mustNot)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

