/*
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.manticoresearch.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.manticoresearch.client.JSON;


/**
 * Response object for successful delete request
 */
@JsonPropertyOrder({
  DeleteResponse.JSON_PROPERTY_INDEX,
  DeleteResponse.JSON_PROPERTY_DELETED,
  DeleteResponse.JSON_PROPERTY_ID,
  DeleteResponse.JSON_PROPERTY_FOUND,
  DeleteResponse.JSON_PROPERTY_RESULT
})
@JsonTypeName("deleteResponse")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-28T14:26:41.232179329Z[Etc/UTC]", comments = "Generator version: 7.3.0-SNAPSHOT")
public class DeleteResponse {
  public static final String JSON_PROPERTY_INDEX = "_index";
  private String index;

  public static final String JSON_PROPERTY_DELETED = "deleted";
  private Integer deleted;

  public static final String JSON_PROPERTY_ID = "_id";
  private Long id;

  public static final String JSON_PROPERTY_FOUND = "found";
  private Boolean found;

  public static final String JSON_PROPERTY_RESULT = "result";
  private String result;

  public DeleteResponse() { 
  }

  public DeleteResponse index(String index) {
    this.index = index;
    return this;
  }

  /**
   * The name of the index from which the document was deleted
   * @return index
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIndex() {
    return index;
  }


  @JsonProperty(JSON_PROPERTY_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndex(String index) {
    this.index = index;
  }


  public DeleteResponse deleted(Integer deleted) {
    this.deleted = deleted;
    return this;
  }

  /**
   * Number of documents deleted
   * @return deleted
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDeleted() {
    return deleted;
  }


  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeleted(Integer deleted) {
    this.deleted = deleted;
  }


  public DeleteResponse id(Long id) {
    this.id = id;
    return this;
  }

  /**
   * The ID of the deleted document. If multiple documents are deleted, the ID of the first deleted document is returned
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Long id) {
    this.id = id;
  }


  public DeleteResponse found(Boolean found) {
    this.found = found;
    return this;
  }

  /**
   * Indicates whether any documents to be deleted were found
   * @return found
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FOUND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getFound() {
    return found;
  }


  @JsonProperty(JSON_PROPERTY_FOUND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFound(Boolean found) {
    this.found = found;
  }


  public DeleteResponse result(String result) {
    this.result = result;
    return this;
  }

  /**
   * Result of the delete operation, typically &#39;deleted&#39;
   * @return result
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResult() {
    return result;
  }


  @JsonProperty(JSON_PROPERTY_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResult(String result) {
    this.result = result;
  }


  /**
   * Return true if this deleteResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteResponse deleteResponse = (DeleteResponse) o;
    return Objects.equals(this.index, deleteResponse.index) &&
        Objects.equals(this.deleted, deleteResponse.deleted) &&
        Objects.equals(this.id, deleteResponse.id) &&
        Objects.equals(this.found, deleteResponse.found) &&
        Objects.equals(this.result, deleteResponse.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(index, deleted, id, found, result);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteResponse {\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    found: ").append(toIndentedString(found)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

