/*
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.manticoresearch.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.manticoresearch.client.JSON;


/**
 * Inline script used to compute a search expression
 */
@JsonPropertyOrder({
  ScriptFieldScript.JSON_PROPERTY_INLINE
})
@JsonTypeName("scriptFieldScript")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-15T06:32:20.081730672Z[Etc/UTC]", comments = "Generator version: 7.17.0")
public class ScriptFieldScript {
  public static final String JSON_PROPERTY_INLINE = "inline";
  private String inline;

  public ScriptFieldScript() { 
  }

  public ScriptFieldScript inline(String inline) {
    this.inline = inline;
    return this;
  }

  /**
   * Expression to compute (same syntax as SQL expressions)
   * @return inline
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INLINE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getInline() {
    return inline;
  }


  @JsonProperty(JSON_PROPERTY_INLINE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInline(String inline) {
    this.inline = inline;
  }

  /**
   * Return true if this scriptFieldScript object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScriptFieldScript scriptFieldScript = (ScriptFieldScript) o;
    return Objects.equals(this.inline, scriptFieldScript.inline);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inline);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScriptFieldScript {\n");
    sb.append("    inline: ").append(toIndentedString(inline)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

