/*
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.manticoresearch.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.manticoresearch.client.JSON;


/**
 * Object containing the search hits, which represent the documents that matched the query.
 */
@JsonPropertyOrder({
  SearchResponseHits.JSON_PROPERTY_MAX_SCORE,
  SearchResponseHits.JSON_PROPERTY_TOTAL,
  SearchResponseHits.JSON_PROPERTY_TOTAL_RELATION,
  SearchResponseHits.JSON_PROPERTY_HITS
})
@JsonTypeName("searchResponse_hits")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-28T14:26:41.232179329Z[Etc/UTC]", comments = "Generator version: 7.3.0-SNAPSHOT")
public class SearchResponseHits {
  public static final String JSON_PROPERTY_MAX_SCORE = "max_score";
  private Integer maxScore;

  public static final String JSON_PROPERTY_TOTAL = "total";
  private Integer total;

  public static final String JSON_PROPERTY_TOTAL_RELATION = "total_relation";
  private String totalRelation;

  public static final String JSON_PROPERTY_HITS = "hits";
  private List<Object> hits;

  public SearchResponseHits() { 
  }

  public SearchResponseHits maxScore(Integer maxScore) {
    this.maxScore = maxScore;
    return this;
  }

  /**
   * Maximum score among the matched documents
   * @return maxScore
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAX_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxScore() {
    return maxScore;
  }


  @JsonProperty(JSON_PROPERTY_MAX_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxScore(Integer maxScore) {
    this.maxScore = maxScore;
  }


  public SearchResponseHits total(Integer total) {
    this.total = total;
    return this;
  }

  /**
   * Total number of matched documents
   * @return total
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotal() {
    return total;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotal(Integer total) {
    this.total = total;
  }


  public SearchResponseHits totalRelation(String totalRelation) {
    this.totalRelation = totalRelation;
    return this;
  }

  /**
   * Indicates whether the total number of hits is accurate or an estimate
   * @return totalRelation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_RELATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTotalRelation() {
    return totalRelation;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_RELATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalRelation(String totalRelation) {
    this.totalRelation = totalRelation;
  }


  public SearchResponseHits hits(List<Object> hits) {
    this.hits = hits;
    return this;
  }

  public SearchResponseHits addItem(Object hitsItem) {
    if (this.hits == null) {
      this.hits = new ArrayList<>();
    }
    this.hits.add(hitsItem);
    return this;
  }

  /**
   * Array of hit objects, each representing a matched document
   * @return hits
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getHits() {
    return hits;
  }


  @JsonProperty(JSON_PROPERTY_HITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHits(List<Object> hits) {
    this.hits = hits;
  }


  /**
   * Return true if this searchResponse_hits object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchResponseHits searchResponseHits = (SearchResponseHits) o;
    return Objects.equals(this.maxScore, searchResponseHits.maxScore) &&
        Objects.equals(this.total, searchResponseHits.total) &&
        Objects.equals(this.totalRelation, searchResponseHits.totalRelation) &&
        Objects.equals(this.hits, searchResponseHits.hits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxScore, total, totalRelation, hits);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchResponseHits {\n");
    sb.append("    maxScore: ").append(toIndentedString(maxScore)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    totalRelation: ").append(toIndentedString(totalRelation)).append("\n");
    sb.append("    hits: ").append(toIndentedString(hits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

