/*
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.manticoresearch.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.manticoresearch.client.model.AggTDigest;
import java.util.Arrays;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AggMedianAbsoluteDeviation
 */
public class AggMedianAbsoluteDeviationTest {
    private final AggMedianAbsoluteDeviation model = new AggMedianAbsoluteDeviation();

    /**
     * Model tests for AggMedianAbsoluteDeviation
     */
    @Test
    public void testAggMedianAbsoluteDeviation() {
        // TODO: test AggMedianAbsoluteDeviation
    }

    /**
     * Test the property 'field'
     */
    @Test
    public void fieldTest() {
        // TODO: test field
    }

    /**
     * Test the property 'tdigest'
     */
    @Test
    public void tdigestTest() {
        // TODO: test tdigest
    }

}
