/*
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.manticoresearch.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.manticoresearch.client.model.AggComposite;
import com.manticoresearch.client.model.AggDateHistogram;
import com.manticoresearch.client.model.AggHistogram;
import com.manticoresearch.client.model.AggMedianAbsoluteDeviation;
import com.manticoresearch.client.model.AggMetric;
import com.manticoresearch.client.model.AggPercentileRanks;
import com.manticoresearch.client.model.AggPercentiles;
import com.manticoresearch.client.model.AggRange;
import com.manticoresearch.client.model.AggTerms;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Aggregation
 */
public class AggregationTest {
    private final Aggregation model = new Aggregation();

    /**
     * Model tests for Aggregation
     */
    @Test
    public void testAggregation() {
        // TODO: test Aggregation
    }

    /**
     * Test the property 'terms'
     */
    @Test
    public void termsTest() {
        // TODO: test terms
    }

    /**
     * Test the property 'sort'
     */
    @Test
    public void sortTest() {
        // TODO: test sort
    }

    /**
     * Test the property 'composite'
     */
    @Test
    public void compositeTest() {
        // TODO: test composite
    }

    /**
     * Test the property 'histogram'
     */
    @Test
    public void histogramTest() {
        // TODO: test histogram
    }

    /**
     * Test the property 'dateHistogram'
     */
    @Test
    public void dateHistogramTest() {
        // TODO: test dateHistogram
    }

    /**
     * Test the property 'range'
     */
    @Test
    public void rangeTest() {
        // TODO: test range
    }

    /**
     * Test the property 'dateRange'
     */
    @Test
    public void dateRangeTest() {
        // TODO: test dateRange
    }

    /**
     * Test the property 'percentiles'
     */
    @Test
    public void percentilesTest() {
        // TODO: test percentiles
    }

    /**
     * Test the property 'percentileRanks'
     */
    @Test
    public void percentileRanksTest() {
        // TODO: test percentileRanks
    }

    /**
     * Test the property 'medianAbsoluteDeviation'
     */
    @Test
    public void medianAbsoluteDeviationTest() {
        // TODO: test medianAbsoluteDeviation
    }

    /**
     * Test the property 'min'
     */
    @Test
    public void minTest() {
        // TODO: test min
    }

    /**
     * Test the property 'max'
     */
    @Test
    public void maxTest() {
        // TODO: test max
    }

    /**
     * Test the property 'sum'
     */
    @Test
    public void sumTest() {
        // TODO: test sum
    }

    /**
     * Test the property 'avg'
     */
    @Test
    public void avgTest() {
        // TODO: test avg
    }

}
