/*
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.manticoresearch.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AggregationCompositeSourcesInnerValueTerms
 */
public class AggregationCompositeSourcesInnerValueTermsTest {
    private final AggregationCompositeSourcesInnerValueTerms model = new AggregationCompositeSourcesInnerValueTerms();

    /**
     * Model tests for AggregationCompositeSourcesInnerValueTerms
     */
    @Test
    public void testAggregationCompositeSourcesInnerValueTerms() {
        // TODO: test AggregationCompositeSourcesInnerValueTerms
    }

    /**
     * Test the property 'field'
     */
    @Test
    public void fieldTest() {
        // TODO: test field
    }

}
