/*
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.manticoresearch.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FulltextFilter
 */
public class FulltextFilterTest {
    private final FulltextFilter model = new FulltextFilter();

    /**
     * Model tests for FulltextFilter
     */
    @Test
    public void testFulltextFilter() {
        // TODO: test FulltextFilter
    }

    /**
     * Test the property 'queryString'
     */
    @Test
    public void queryStringTest() {
        // TODO: test queryString
    }

    /**
     * Test the property 'match'
     */
    @Test
    public void matchTest() {
        // TODO: test match
    }

    /**
     * Test the property 'matchPhrase'
     */
    @Test
    public void matchPhraseTest() {
        // TODO: test matchPhrase
    }

    /**
     * Test the property 'matchAll'
     */
    @Test
    public void matchAllTest() {
        // TODO: test matchAll
    }

}
