/*
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 3.3.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.manticoresearch.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.manticoresearch.client.model.GeoDistanceFilterLocationAnchor;
import java.util.Arrays;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GeoDistanceFilter
 */
public class GeoDistanceFilterTest {
    private final GeoDistanceFilter model = new GeoDistanceFilter();

    /**
     * Model tests for GeoDistanceFilter
     */
    @Test
    public void testGeoDistanceFilter() {
        // TODO: test GeoDistanceFilter
    }

    /**
     * Test the property 'locationAnchor'
     */
    @Test
    public void locationAnchorTest() {
        // TODO: test locationAnchor
    }

    /**
     * Test the property 'locationSource'
     */
    @Test
    public void locationSourceTest() {
        // TODO: test locationSource
    }

    /**
     * Test the property 'distanceType'
     */
    @Test
    public void distanceTypeTest() {
        // TODO: test distanceType
    }

    /**
     * Test the property 'distance'
     */
    @Test
    public void distanceTest() {
        // TODO: test distance
    }

}
