/*
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.manticoresearch.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for HighlightFieldOption
 */
public class HighlightFieldOptionTest {
    private final HighlightFieldOption model = new HighlightFieldOption();

    /**
     * Model tests for HighlightFieldOption
     */
    @Test
    public void testHighlightFieldOption() {
        // TODO: test HighlightFieldOption
    }

    /**
     * Test the property 'fragmentSize'
     */
    @Test
    public void fragmentSizeTest() {
        // TODO: test fragmentSize
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'limitSnippets'
     */
    @Test
    public void limitSnippetsTest() {
        // TODO: test limitSnippets
    }

    /**
     * Test the property 'limitWords'
     */
    @Test
    public void limitWordsTest() {
        // TODO: test limitWords
    }

    /**
     * Test the property 'numberOfFragments'
     */
    @Test
    public void numberOfFragmentsTest() {
        // TODO: test numberOfFragments
    }

}
