/*
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 3.3.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.manticoresearch.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MatchOpFilter
 */
public class MatchOpFilterTest {
    private final MatchOpFilter model = new MatchOpFilter();

    /**
     * Model tests for MatchOpFilter
     */
    @Test
    public void testMatchOpFilter() {
        // TODO: test MatchOpFilter
    }

    /**
     * Test the property 'queryString'
     */
    @Test
    public void queryStringTest() {
        // TODO: test queryString
    }

    /**
     * Test the property 'queryFields'
     */
    @Test
    public void queryFieldsTest() {
        // TODO: test queryFields
    }

    /**
     * Test the property 'operator'
     */
    @Test
    public void operatorTest() {
        // TODO: test operator
    }

}
