/*
 * Manticore Search Client
 * Low-level client for Manticore Search. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.manticoresearch.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NotFilterString
 */
public class NotFilterStringTest {
    private final NotFilterString model = new NotFilterString();

    /**
     * Model tests for NotFilterString
     */
    @Test
    public void testNotFilterString() {
        // TODO: test NotFilterString
    }

    /**
     * Test the property 'filterField'
     */
    @Test
    public void filterFieldTest() {
        // TODO: test filterField
    }

    /**
     * Test the property 'operation'
     */
    @Test
    public void operationTest() {
        // TODO: test operation
    }

    /**
     * Test the property 'filterValue'
     */
    @Test
    public void filterValueTest() {
        // TODO: test filterValue
    }

}
