/*
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.manticoresearch.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Range
 */
public class RangeTest {
    private final Range model = new Range();

    /**
     * Model tests for Range
     */
    @Test
    public void testRange() {
        // TODO: test Range
    }

    /**
     * Test the property 'lt'
     */
    @Test
    public void ltTest() {
        // TODO: test lt
    }

    /**
     * Test the property 'lte'
     */
    @Test
    public void lteTest() {
        // TODO: test lte
    }

    /**
     * Test the property 'gt'
     */
    @Test
    public void gtTest() {
        // TODO: test gt
    }

    /**
     * Test the property 'gte'
     */
    @Test
    public void gteTest() {
        // TODO: test gte
    }

}
