/*
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 3.3.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.manticoresearch.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RangeFilter
 */
public class RangeFilterTest {
    private final RangeFilter model = new RangeFilter();

    /**
     * Model tests for RangeFilter
     */
    @Test
    public void testRangeFilter() {
        // TODO: test RangeFilter
    }

    /**
     * Test the property 'field'
     */
    @Test
    public void fieldTest() {
        // TODO: test field
    }

    /**
     * Test the property 'lte'
     */
    @Test
    public void lteTest() {
        // TODO: test lte
    }

    /**
     * Test the property 'gte'
     */
    @Test
    public void gteTest() {
        // TODO: test gte
    }

    /**
     * Test the property 'lt'
     */
    @Test
    public void ltTest() {
        // TODO: test lt
    }

    /**
     * Test the property 'gt'
     */
    @Test
    public void gtTest() {
        // TODO: test gt
    }

}
