/*
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.manticoresearch.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.manticoresearch.client.model.Aggregation;
import com.manticoresearch.client.model.Highlight;
import com.manticoresearch.client.model.Join;
import com.manticoresearch.client.model.KnnQuery;
import com.manticoresearch.client.model.SearchQuery;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SearchRequest
 */
public class SearchRequestTest {
    private final SearchRequest model = new SearchRequest();

    /**
     * Model tests for SearchRequest
     */
    @Test
    public void testSearchRequest() {
        // TODO: test SearchRequest
    }

    /**
     * Test the property 'table'
     */
    @Test
    public void tableTest() {
        // TODO: test table
    }

    /**
     * Test the property 'query'
     */
    @Test
    public void queryTest() {
        // TODO: test query
    }

    /**
     * Test the property 'join'
     */
    @Test
    public void joinTest() {
        // TODO: test join
    }

    /**
     * Test the property 'highlight'
     */
    @Test
    public void highlightTest() {
        // TODO: test highlight
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'knn'
     */
    @Test
    public void knnTest() {
        // TODO: test knn
    }

    /**
     * Test the property 'aggs'
     */
    @Test
    public void aggsTest() {
        // TODO: test aggs
    }

    /**
     * Test the property 'expressions'
     */
    @Test
    public void expressionsTest() {
        // TODO: test expressions
    }

    /**
     * Test the property 'maxMatches'
     */
    @Test
    public void maxMatchesTest() {
        // TODO: test maxMatches
    }

    /**
     * Test the property 'offset'
     */
    @Test
    public void offsetTest() {
        // TODO: test offset
    }

    /**
     * Test the property 'options'
     */
    @Test
    public void optionsTest() {
        // TODO: test options
    }

    /**
     * Test the property 'profile'
     */
    @Test
    public void profileTest() {
        // TODO: test profile
    }

    /**
     * Test the property 'sort'
     */
    @Test
    public void sortTest() {
        // TODO: test sort
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'trackScores'
     */
    @Test
    public void trackScoresTest() {
        // TODO: test trackScores
    }

}
