/*
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.manticoresearch.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.manticoresearch.client.model.KnnQueryByDocId;
import com.manticoresearch.client.model.KnnQueryByVector;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SearchRequestKnn
 */
public class SearchRequestKnnTest {
    private final SearchRequestKnn model = new SearchRequestKnn();

    /**
     * Model tests for SearchRequestKnn
     */
    @Test
    public void testSearchRequestKnn() {
        // TODO: test SearchRequestKnn
    }

    /**
     * Test the property 'field'
     */
    @Test
    public void fieldTest() {
        // TODO: test field
    }

    /**
     * Test the property 'queryVector'
     */
    @Test
    public void queryVectorTest() {
        // TODO: test queryVector
    }

    /**
     * Test the property 'k'
     */
    @Test
    public void kTest() {
        // TODO: test k
    }

    /**
     * Test the property 'filter'
     */
    @Test
    public void filterTest() {
        // TODO: test filter
    }

    /**
     * Test the property 'docId'
     */
    @Test
    public void docIdTest() {
        // TODO: test docId
    }

}
