/*
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.manticoresearch.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SourceByRules
 */
public class SourceByRulesTest {
    private final SourceByRules model = new SourceByRules();

    /**
     * Model tests for SourceByRules
     */
    @Test
    public void testSourceByRules() {
        // TODO: test SourceByRules
    }

    /**
     * Test the property 'includes'
     */
    @Test
    public void includesTest() {
        // TODO: test includes
    }

    /**
     * Test the property 'excludes'
     */
    @Test
    public void excludesTest() {
        // TODO: test excludes
    }

}
