name: Publishing

on: [push]

jobs:
  test:
    uses: ./.github/workflows/test.yml
  publish:
    name: Publish the client to the public registry
    needs: [test]
    runs-on: ubuntu-22.04
    env:
      MVNSETTINGS: ${{ secrets.MVNSETTINGS }}
      PRIVATEKEY: ${{ secrets.PRIVATEKEY }}
      GPGKEY: ${{ secrets.GPGKEY }}
    strategy:
      matrix:
        java: [ '17' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
    - name: Use Maven
      run: |
        mkdir -p ~/.m2
        export GPG_TTY=$(tty)
        export MAVEN_OPTS="--add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED"
        echo "$MVNSETTINGS" > ~/.m2/settings.xml
        echo "import" 
        echo "$PRIVATEKEY" > ~/key
        gpg2 --import --batch ~/key
        echo "verify"
        mvn install -Dmaven.test.skip.exec=true -DskipTests=true -Dmaven.test.skip=true -Dgpg.passphrase=$GPGKEY
        echo "deploy"
        mvn clean deploy -e -X
